### ISSUE TITLE
Technica Daemon interfaced with Ixexplorer's MKA daemon has key exchange issues

### ISSUE THREAD

**Issue by ashravti** [Technica-Engineering/MKAdaemon#6]
Hi,

We are having a setup like the below : 

Linux PC (having software macsec, and Technica's MKA daemon to do the MKA) < --- RJ 45 --- > Ixia packet generator (hosting native Ixia MKA daemon capable of MKA).

We see an issue as reported : (attaching a word document capturing the details of the issue of incompatibility of the two daemons). Since any MKA daemon should be standard and adhering to IEEE 802.1x 2020, we would like to check if there has been any misinterpretation of the specification by Technica as required by IEEE.

Thanks,
Ashwin
[technica_daemon--interfaced--with--Ixia_daemon.docx](https://github.com/Technica-Engineering/MKAdaemon/files/10791364/technica_daemon--interfaced--with--Ixia_daemon.docx)

**Comment by andreu-montiel-te** [comment]
Hi Ashwin,

Thanks for the report!

I have analysed what you mentioned. The sequence of events that happens in our daemon in regards to installation of the first key is as follows:
 -> Once a new SAK is distributed, the path from RECEIVING to TRANSMITTING depends on whether we are key server or not, but anyway we end up in TRANSMITTING anyway immediately, given that controlledPortEnabled = FALSE.
 -> In TRANSMITTING state entry steps, the assignment "retireWhen = (orx ? retireDelay : 0)" is = 0 . This is because orx = FALSE (there is no previous old key), the timer to transition from TRANSMITTING to RETIRE is set to 0, immediate.
 -> Transition from TRANSMITTING to RETIRE happens immediately because the first OR'd condition is evaluated as true (retireWhen == 0), as per spec.
 -> In RETIRE state entry commands,  "last" identifiers are transitioned to "old" in RETIRE state.

No more transitions are taken, this state is stable, and as a result, KAY transmits "old" parameters during the distribution of the first key while CP is in this state RETIRE. They would be transmitted as "last" but only during rekeys because then orx == TRUE and therefore retireWhen will no longer be 0. As per my understanding this behavior seems aligned with 802.1X 2020 (version 2010 looks like has the same CP FSM)  .

In the trace provided, Ixia daemon is transmitting ltx = False, lrx = True. I also see they distribute a SAK so they're acting as key server. It looks like their CP FSM was in state RECEIVING while transmitting that MKPDU. 
In my opinion the transition should have already happened because electedSelf = TRUE, and controlledPortEnable = FALSE, which is sufficient to transition to TRANSMIT. It is strange since this transition doesn't depend on a potentially slow PHY or slow crypto modules (which would explain why they're still there), but variables that should be available to read.

Maybe they're evaluating their CP FSM slower than our daemon and transmitting MKPDU's in intermediate states? How long do they stay in those intermediate states?

Another question I have, does this difference of speed evaluating CP FSM transitions affect negotiation of keys between our daemon and Ixia implementation? Or is it just a difference you observed analysing the traces?

Thanks!
Andreu

**Comment by ashravti** [comment]
Hi Andreu,

I am debugging this with the Keysight support team, shall let you know soon about the questions you had raised.
Meanwhile i wanted to check if the Technica Daemon has been checked with wpa_supplicant on the other end.

Linux PC1 (running technica daemon) < --- > Linux PC2 (running wpa_supplicant)

Does the above setup work ?

Thanks,
Ashwin

**Comment by andreu-montiel-te** [comment]
Hi Ashwin,

In the past we tried with hostapd it worked perfectly.

BR,
Andreu

**Comment by dkrabort** [comment]
> Hi Ashwin,
> 
> Thanks for the report!
> 
> I have analysed what you mentioned. The sequence of events that happens in our daemon in regards to installation of the first key is as follows: -> Once a new SAK is distributed, the path from RECEIVING to TRANSMITTING depends on whether we are key server or not, but anyway we end up in TRANSMITTING anyway immediately, given that controlledPortEnabled = FALSE. -> In TRANSMITTING state entry steps, the assignment "retireWhen = (orx ? retireDelay : 0)" is = 0 . This is because orx = FALSE (there is no previous old key), the timer to transition from TRANSMITTING to RETIRE is set to 0, immediate. -> Transition from TRANSMITTING to RETIRE happens immediately because the first OR'd condition is evaluated as true (retireWhen == 0), as per spec. -> In RETIRE state entry commands, "last" identifiers are transitioned to "old" in RETIRE state.
> 
> No more transitions are taken, this state is stable, and as a result, KAY transmits "old" parameters during the distribution of the first key while CP is in this state RETIRE. They would be transmitted as "last" but only during rekeys because then orx == TRUE and therefore retireWhen will no longer be 0. As per my understanding this behavior seems aligned with 802.1X 2020 (version 2010 looks like has the same CP FSM) .
> 
> In the trace provided, Ixia daemon is transmitting ltx = False, lrx = True. I also see they distribute a SAK so they're acting as key server. It looks like their CP FSM was in state RECEIVING while transmitting that MKPDU. In my opinion the transition should have already happened because electedSelf = TRUE, and controlledPortEnable = FALSE, which is sufficient to transition to TRANSMIT. It is strange since this transition doesn't depend on a potentially slow PHY or slow crypto modules (which would explain why they're still there), but variables that should be available to read.
> 
> Maybe they're evaluating their CP FSM slower than our daemon and transmitting MKPDU's in intermediate states? How long do they stay in those intermediate states?
> 
> Another question I have, does this difference of speed evaluating CP FSM transitions affect negotiation of keys between our daemon and Ixia implementation? Or is it just a difference you observed analysing the traces?
> 
> PS: Just a follow up note, bear in mind this implementation is optimised for automotive use cases and tries to accelerate negotiation where possible while still complying with IEEE802.1X.
> 
> Thanks! Andreu

Hi Andrew,

When Technica is not the keyserver, and it receives a distributed SAK, it should move from RECEIVE->RECEIVING->READY state (since electedself is false). In READY state, newInfo=True. This should signal a MKPDU transmission. Again in the TRANSMITTING state, newInfo is set to True. This should again signal a MKPDU transmission. Since during this time, the latest key is active, shouldn't the SAK_USE parameter in the MKPDUs reflect the latest key properties (ltx/lrx) ?

Thanks,
Dibyendu

**Comment by andreu-montiel-te** [comment]
Hi Dibyendu,

Mostly I agree with you, but I think the key point here is the difference of understanding in the behavior of "newInfo". As we understood, this is a request flag that can be set but doing so does not stop CP from running.  In other words, we do not consider setting newInfo=TRUE as a "function call", for us is just setting a flag. I suspect as per your understanding, setting newInfo=TRUE should block CP from transitioning, but we didn't find that statement anywhere in IEEE 802.1X.

An example of an explicit delay, state RECEIVE. It is clear that CP must wait until reception SA is ready (transition requires "usingReceiveSAs"). However, there is no condition like "MKPDU transmitted", or "newInfo == FALSE" to transition further in state READY or TRANSMITTING.

Later after CP execution finishes, newInfo flag is attended by KAY. At that point, CP is in state RETIRE, so otx/orx are transmitted.

Of course it is possible we missed something in the spec, please let us know.

BR,
Andreu

**Comment by andreu-montiel-te** [comment]
Hello @ashravti / @dkrabort , any update?

BR,
Andreu

**Comment by andreu-montiel-te** [comment]
Hello, I'll close this ticket after 6 weeks of inactivity. Feel free to open a new one if you find a problem.
