### ISSUE TITLE
MACsec Desired and MACsec Capability are setting to False after distributed SAK.

### ISSUE THREAD

**Issue by anileit** [Technica-Engineering/MKAdaemon#7]
Hi

I have the below setup.
Linux PC (VM/22.04.1-Ubuntu) with Technica's MKA daemon<----->MKA+MACsec Software

MACsec Desired and MACsec Capability are setting to False after distributed SAK in MKPDU sent from Technica's MKA daemon.
This is happening when Technica's MKA daemon is keyserver or non keyserver.

Before distributed SAK:
========================
.1.. .... = MACsec Desired: True
..01 .... = MACsec Capability: MACsec Integrity without confidentiality (1)

After distributed SAK:
======================
.0.. .... = MACsec Desired: False
..00 .... = MACsec Capability: MACsec not implemented (0)

Can you please help if there is any config issue ? Attaching config file used in Technica's MKA daemon.

**Comment by anileit** [comment]
[
[mka_config.txt](https://github.com/Technica-Engineering/MKAdaemon/files/10823886/mka_config.txt)
![After_Distributed SAK](https://user-images.githubusercontent.com/3875831/221175572-729d5aab-b52b-4952-b4c8-b8556f68645f.JPG)
![Before_Distributed SAK](https://user-images.githubusercontent.com/3875831/221175579-afe8296c-c75e-4a07-9799-1328613d1b81.JPG)
](url)

**Comment by andreu-montiel-te** [comment]
Hi @anileit ,

To analyse the issue,would it be possible to also have a full debug log? Just run it with arguments -fv 3, something like this:
`./build/mkad -fv 3 -c mkad.conf | tee mkad.log`

Thanks!
Andreu

**Comment by anileit** [comment]
Attached 

Thanks,
Anil
[mkad.log](https://github.com/Technica-Engineering/MKAdaemon/files/10824026/mkad.log)

**Comment by anileit** [comment]
attaching logs with -v 3
[mkad_v3.log](https://github.com/Technica-Engineering/MKAdaemon/files/10824075/mkad_v3.log)

**Comment by andreu-montiel-te** [comment]
Having a quick look it looks like mkad is actively deciding to ignore MKPDU's from the peer because it considers the announcements are malformed. As a result the negotiation is not completed correctly.

The MKPDU's of the peer fail a sanity check of the length of the announcement parameter against the lengths of the TLVs contained in it. Could you share the PCAP traces as well?

**Comment by anileit** [comment]
[mka_debug.zip](https://github.com/Technica-Engineering/MKAdaemon/files/10824250/mka_debug.zip)

Please find the capture.

**Comment by andreu-montiel-te** [comment]
![image](https://user-images.githubusercontent.com/113546767/221185759-d6773cf5-0ced-4a68-a6b1-1d1638cb4bf8.png)
Here's the problem, the field "TLV information string length" is 224 which exceeds the announcement parameter.
I'm not sure if I'm missing something but looks like this is a non IEEE802.1X compliant parameter?

Andreu

**Comment by anileit** [comment]
Thanks Andreu.

**Comment by anileit** [comment]
Can you please help to check  mka/macsec statistics like below in Technica's  ?
Is there any help document with commands to check MKA/MACsec statistics ?

SAK Rx Statistics for AN [3]:
   Unchecked Pkts: 0
   Delayed Pkts: 0
   Late Pkts: 0
   OK Pkts: 1
   Invalid Pkts: 0
   Not Valid Pkts: 0
   Not-Using-SA Pkts: 0
   Unused-SA Pkts: 0
   Decrypted In-Octets: 235 bytes
   Validated In-Octets: 0 bytes

**Comment by andreu-montiel-te** [comment]
Hi Anil,
Unfortunately there is no document, but all the statistics are published via D-BUS. You have an example of a D-BUS client here https://github.com/Technica-Engineering/MKAdaemon/blob/main/src/mkad_cli/main.c . If you have compiled the project, the resulting binary of this client is build/mkad_cli.

BR,
Andreu

**Comment by anileit** [comment]
it's giving error when running command: mkad_cli -i
Error: Could not connect mkad daemon via dbus. Is it running and connected to dbus?

**Comment by jauge-technica** [comment]
Hello,
The error message you're getting simply means the mkad_cli, which is a dbus client, could not communicate via dbus with the server, which is mkad. This can be for a number of reasons.
* Both mkad and mkad_cli need to run as root, because they're accessing the system bus (and not the session bus)
* If you're in a desktop system, you may use another tool such as d-feet to check the dbus directly
* Some dbus daemons require a policy file to grant explicit permission to allow registering a bus name. If your daemon requires a policy, you can use the one that's bundled in the mkad code like this:
    * cp dbus-policies/de.technica_engineering.mkad.conf /usr/share/dbus-1/system.d/de.technica_engineering.mkad.conf
* Check the log at the startup of mkad for any errors when the bus name is being registered.

**Comment by andreu-montiel-te** [comment]
Hello @anileit  , any update?

BR,
Andreu

**Comment by anileit** [comment]
Hi Andreu,
I was able to verify the required mka/macsec statistics.
Thanks for your help.
